### ISSUE TITLE
unresponsive submodule update

### ISSUE THREAD

**Issue by ryanslabxyz** [groovemonkey/hands-on-ansible#3]
Hello, I'm at the beginning of your Ansible 2 for beginners video series.  After I clone the ansible repo from github, you instruct to do a `git submodule update --init --recursive`. This doesn't do anything and my command line starts on a new line.  I'm using  an Ubuntu 16 desktop VM and git version 2.7.4.  I pulled the latest Ansible repo as of today. Why doesn't anything happen? Does the repo no longer use submodules? I'm familiar with git but not so much with submodules in git. Thank you for your attention.

**Comment by groovemonkey** [comment]
Just realized that I sent this in an e-mail but didn't post it here:

You're absolutely right -- the structure of the Ansible repository has
changed and that's no longer necessary AFAIK. I'll edit the instructions to remove that.

Honestly the best way to install Ansible at this point is using the
python-venv installation method:
https://tutorialinux.com/install-ansible-ubuntu-linux/

It's just a few steps and it's the lowest-drama way to install Ansible.

I hope that helps!

**Comment by ryanslabxyz** [comment]
Thank you for the information. I used the apt-get method instead. I'll try the python method next.
